-- Define hlasm virtual files buffer read command.
-- Source generated by AINSERT or preprocessors can be retrieved
-- from the hlasm language server via a custom LSP request.
-- This buffer read command makes it possible to view the content.

local hlasm_group = vim.api.nvim_create_augroup("hlasm", {})
vim.api.nvim_create_autocmd('BufReadCmd', {
    group = hlasm_group,
    pattern = "hlasm://*",
    callback = function (args)
        local client = vim.lsp.get_clients({ name = "hlasm" })[1]
        if client == nil then
            return
        end

        local buf = args.buf

        vim.bo[buf].swapfile = false
        vim.bo[buf].buftype = 'nofile'

        local id = args.match:match("^%w+://([^/?#]+)")

        local resp = client:request_sync('get_virtual_file_content', { id = tonumber(id) })
        if resp == nil or resp.err ~= nil then
            return
        end

        local source_lines = vim.fn.split(resp.result.content, [[\r\?\n]])

        vim.api.nvim_buf_set_lines(buf, 0, -1, false, source_lines)
        vim.bo[buf].modifiable = false
    end,
})
